import type { NextPage } from "next";
import Head from "next/head";
import FooterComponent from "../components/common/footer/footer";
import HeaderComponent from "../components/common/header/header";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />

      <main className="p-10">Startseite</main>

      <FooterComponent />
    </div>
  );
};

export default Home;
