import type { NextPage } from "next";
import Head from "next/head";
import FooterComponent from "../components/common/footer/footer";
import HeaderComponent from "../components/common/header/header";
import Image from "next/image";
import test from "../public/test.jpg";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />

      <main className="p-10">
        <Image
          objectFit="cover"
          alt="Vercel logo"
          placeholder="blur"
          src={test}
          width={1000}
          height={1000}
        />
      </main>

      <FooterComponent />
    </div>
  );
};

export default Home;
